Vertex meta data changes
vert-x3/vertx-consul-client pull request #111
Opened 2024-09-26 08:44 UTC by paras-amdocs-openet

The changes made to the vertx consul client for the extended meta data changes

Motivation:

If there was an external service that needed to register more than 64 meta data entries (for routing i.e. IPv6 prefix ranges), the NFRA would simply fail to register that service instance. 

Solution
If the NFRA detects that more than 64 meta data entries are needed, then all meta data is stored in a KV entry, rather than the service instance meta data storage. 
The service instance meta data storage has a single entry, which points to the KV store entry key, holding the actual meta data.

2024-09-27 03:07 UTC, ruslansennov requested changes

2024-09-27 06:23 UTC, ruslansennov approved these changes

2024-09-27 06:23 UTC, ruslansennov commented
@paras-amdocs-openet could you sign the agreement?

2024-10-03 06:25 UTC, paras-amdocs-openet commented
Hi @ruslansennov 

I have signed the agreement.

Thanks.

2024-10-03 12:30 UTC, merged

2024-10-03 12:31 UTC, ruslansennov commented
@paras-amdocs-openet thank you!

We should also move these commits to master (v.5.0).
Can you do that?